Pin the uid and gid of the legacy container to a fixed value
inmanta/inmanta pull request #131
Opened 2024-07-02 13:45 UTC by arnaudsjs

# Description

Pin the uid and gid of the legacy container to a fixed value.

Part of inmanta/inmanta-core#7674

# Self Check:

- [x] Attached issue to pull request
- [x] Changelog entry

2024-07-02 14:04 UTC, edvgui requested changes
In this PR we also need to update the documentation.  We were making the assumption that the inmanta uid and gid where 993 in multiple places (in the podman installation instructions), such as https://github.com/inmanta/inmanta-core/blob/34934c43c12b7532302df02caa3a3fd60920e4cc/docs/install/2-install-server-with-podman-and-systemd.rst?plain=1#L356

2024-07-02 14:38 UTC, edvgui approved these changes

2024-07-03 07:04 UTC, hlloreda approved these changes

2024-07-03 07:06 UTC, inmantaci commented
Processing this pull request

2024-07-03 07:06 UTC, inmantaci commented
Merged into branches master in f7a773319ce6739ef849268a23eb822b1642c14f

2024-07-03 07:06 UTC, closed without merging