Update installation instructions native docker container
inmanta/inmanta pull request #143
Opened 2024-12-18 10:52 UTC by DariushMoh

# Description

Related to https://github.com/inmanta/inmanta-core/issues/8304#issue-2632714023

# Self Check:

- [ ] Attached issue to pull request
- [ ] Changelog entry

2024-12-18 14:35 UTC, arnaudsjs requested changes

2024-12-18 14:35 UTC, arnaudsjs commented on changelogs/unreleased/changelogs/unreleased/8304-update-installation-instructions-native-docker-container.yml
> +        - Server options --wait-for-host and --wait-for-port are now ignored. They are now provided in env variables.
Same here.

2024-12-18 15:23 UTC, arnaudsjs requested changes

2024-12-18 15:23 UTC, arnaudsjs commented on changelogs/unreleased/changelogs/unreleased/8304-update-installation-instructions-native-docker-container.yml
> +      The iso 8 orchestrator image introduces a number of changes, including these breaking changes:
This is the changelog entry for OSS. So we cannot talk about iso8 here. I would use the actual name of the image here.

2025-01-02 09:52 UTC, arnaudsjs requested changes

2025-01-02 09:52 UTC, arnaudsjs commented on changelogs/unreleased/changelogs/unreleased/8304-update-installation-instructions-native-docker-container.yml
> +destination-branches: [master]
You are missing the `issue-repo` here, because the repo of the PR is not the same as the repo of the issue.

2025-01-02 15:29 UTC, arnaudsjs approved these changes

2025-01-02 15:31 UTC, arnaudsjs requested changes

2025-01-02 15:31 UTC, arnaudsjs commented on changelogs/unreleased/changelogs/unreleased/8304-update-installation-instructions-native-docker-container.yml
> +    The image inmanta/orchestrator:8 introduces a number of changes, including these breaking changes:
This version number isn't correct. OSS works with `<year>.<release-nr>` versioning. The next release will be `2025.1`.

2025-01-02 15:45 UTC, DariushMoh commented on changelogs/unreleased/changelogs/unreleased/8304-update-installation-instructions-native-docker-container.yml
> +    The image inmanta/orchestrator:8 introduces a number of changes, including these breaking changes:
Interesting, I was completely unaware of that.

2025-01-03 06:34 UTC, arnaudsjs approved these changes

2025-01-03 08:06 UTC, inmantaci commented
Processing this pull request

2025-01-03 08:06 UTC, inmantaci commented
Pull request rejected by merge tool. No change entry file found

2025-01-03 08:14 UTC, inmantaci commented
Processing this pull request

2025-01-03 08:14 UTC, inmantaci commented
Merged into branches master in b4f89b73829d56b16ad89835b4af5e7f47961a4d

2025-01-03 08:14 UTC, closed without merging