Fixing option checking
inmanta/inmanta pull request #2525
Opened 2020-11-23 07:09 UTC by edvgui

# Description

Fixes the bug that made `inmanta export` fail when `--server_address` was set.

closes #2514 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] ~~Changelog entry~~
- [ ] ~~Type annotations are present~~
- [ ] ~~Code is clear and sufficiently documented~~
- [ ] ~~No (preventable) type errors (check using make mypy or make mypy-diff)~~
- [ ] ~~Sufficient test cases (reproduces the bug/tests the requested feature)~~
- [ ] ~~Correct, in line with design~~
- [ ] ~~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2020-11-23 07:29 UTC, arnaudsjs requested changes
Please add:
* Changelog entry
* Test case

2020-11-23 09:36 UTC, sanderr approved these changes

2020-11-24 09:08 UTC, edvgui commented
@arnaudsjs Actually, this argument is already being tested: https://github.com/inmanta/inmanta/blob/issue/2515-server-address-option/tests/test_app_cli.py#L186

How is it that the tests where not failing before?

2020-11-24 09:28 UTC, arnaudsjs commented
The error only occurs when server is set but not port. When both are set together, everything works fine.

2020-11-24 12:19 UTC, arnaudsjs approved these changes

2020-11-24 12:25 UTC, merged